### ISSUE TITLE
[English support]: call to undefined function gmp_ini()

### ISSUE THREAD

**Issue by Datoby92** [pangolp/support#8]
# Wow-CMS English support

### What operating system are you using?
- [x] Windows

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] Localhost

### Which emulator are you using and which version?
- [x] AzerothCore

### Describe the bug
- After fresh install i have problem inclued on my screen

### Screenshots
![QYHN1](https://user-images.githubusercontent.com/2810187/118372917-502a5d00-b58a-11eb-9567-f63d07b9c33c.png)

**Comment by Datoby92** [comment]
This problems appear when trying register or login

**Comment by pangolp** [comment]
The error occurs because the `php_gmp` dependency is missing. The problem is that if it is in `Windows`, you only have to inhabit it, eliminating the `;` from the beginning of the file. In the case of Linux, it would have been different.

![gmp](https://user-images.githubusercontent.com/2810187/118373156-bc599080-b58b-11eb-841a-996316b46f74.png)
