### ISSUE TITLE
[English support]: When i add realm to realmlist

### ISSUE THREAD

**Issue by Datoby92** [pangolp/support#9]
# Wow-CMS English support

### What operating system are you using?
- [x] Windows

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] VPS

### Which emulator are you using and which version?
- [x] AzerothCore

### Describe the bug

```
An uncaught Exception was encountered
Type: Error

Message: Call to a member function num_rows() on bool

Filename: C:\xampp\htdocs\application\models\Realm_model.php

Line Number: 186

Backtrace:

File: C:\xampp\htdocs\application\modules\home\views\home.php
Line: 90
Function: getCharactersOnlineAlliance

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 588
Function: include

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 506
Function: _ci_load

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 802
Function: view

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 763
Function: _load_view

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 286
Function: _find_view

File: C:\xampp\htdocs\application\modules\home\controllers\Home.php
Line: 80
Function: build

File: C:\xampp\htdocs\index.php
Line: 319
Function: require_once
```

**Comment by pangolp** [comment]
Normally this error is caused by a bug in the CMS, at the moment of saving the passwords of the realms. That's something that sometimes I really forget that it's still there, but as it's a rare error, usually after chatting about it, I continue with another topic.

The reasons for that bug usually have to do with the password.
`If it is too external or if it has special characters.`

Anyway, it is a CMS bug, which should be corrected.
But for the moment, we would have to check that to corroborate if that is the issue.

**Comment by pangolp** [comment]
@Datoby92 Is the problem solved?

**Comment by pangolp** [comment]
I don't remember well, but I think the problem had been recall. Any future problems, please open a new issue. Thank you.
